apiVersion: v1
kind: Pod
metadata:
  name: minegocioapp-pod
  labels:
    app: minegocioapp
    type: microservice
spec:
  containers:
    - name: minegocioapp
      image: frankdevg/minegocio:1.3
      ports:
        - containerPort: 8080
      env:
        - name: Postgres__ConecctionString
          value: User ID=postgres;Password=258456;Host=10.0.97.223;Port=5432;Database=minegocio;